Add support for multiple batteries

diff --git a/battery-monitor b/battery-monitor
--- a/battery-monitor
+++ b/battery-monitor
@@ -2,7 +2,7 @@
 # Author: Pooya Moradi
 # Date : 2022-08-27 | 1401-06-05
 #
-# Description: Plot power consumption of batteries of the laptop.
+# Description: plot power consumption of batteries of the laptop.
 # Dependencies: feedgnuplot, yad, awk
 
 # enforce run of only a single instance of the script
@@ -12,7 +12,7 @@ if ! mkdir -- "$lockfile"; then
     exit 1
 fi
 
-version=0.3
+version=0.4
 period="1"
 window="30"
 gnuplot_terminal="qt font 'monospace,10'"
@@ -65,6 +65,32 @@ check_deps() {
     return "$err"
 }
 
+get_battery_powers() {
+    if ((step == 0)); then
+        batteries=$(find /sys/class/power_supply/ -iname "BAT[0-9]*" -printf "%f\n")
+        if [[ -z "$batteries" ]]; then
+            printf >&2 "[ERROR] Can't find active batteries.\n"
+            return 1
+        fi
+        printf "#%s %s\n" "Step" \
+            "$(printf "%s" "$batteries" | tr '\n' ' ')"
+        return
+    fi
+    cat /sys/class/power_supply/BAT*/power_now \
+        | tr '\n' ' '
+}
+
+test_gen_data() {
+    if ((step == 0)); then
+        printf "#%s %s\n" "Step" "BAT0 BAT1 BAT2"
+        return
+    fi
+    printf "%s %s %s\n" \
+        "$(shuf -i 1000000-10000000 -n 1)" \
+        "$(shuf -i 10000000-20000000 -n 1)" \
+        "$(shuf -i 20000000-30000000 -n 1)"
+}
+
 while getopts t:w:Vh opt; do
     case $opt in
         h)
@@ -82,8 +108,7 @@ while getopts t:w:Vh opt; do
             window="$OPTARG"
             ;;
         *)
-            printf >&2 "[ERROR] Bad usage!\n"
-            show_help >&2
+            printf >&2 "[ERROR] Bad usage! Check help (-h)\n"
             exit 2
             ;;
     esac
@@ -101,18 +126,25 @@ printf "%s|\n" \
     >&3
 
 # produce data with cat and consume with feedgnuplot
+step=0
 while true; do
     # convert p1\np2 to p1,p2, then divide by 1e6 to convert to Watts
-    line=$(cat /sys/class/power_supply/{BAT0,BAT1}/power_now \
-        | paste --serial --delimiters=',' \
-        | awk -F ',' '{print $1/1e6, $2/1e6}')
+    line=$(get_battery_powers \
+        | awk -F ' ' -v step="$step" \
+            '{if (step == 0) print $0;
+              else {
+                   for(i=1; i<=NF; i++) $i=$i/1e6;
+                   print step, $0 }
+                }')
     printf "tooltip: %s\n" "$line" >&3
     printf "%s\n" "$line"
     sleep "$period"
+    step=$((step + 1))
 done \
-    | feedgnuplot --stream "$period" --xlen "$window" \
+    | feedgnuplot --vnlog --autolegend --domain \
+        --stream "$period" --xlen "$window" \
         --lines --set "ylabel 'Power consumption [Watt]'" \
-        --legend 0 "BAT0" --legend 1 "BAT1" --set 'key bottom left' \
+        --set 'key bottom left' \
         --styleall 'with lines linewidth 3' \
         --terminal "$gnuplot_terminal" \
         --exit
